### PR TITLE
Refactor code, fix logic bugs, complete missing implementations

### PR DESCRIPTION
**Pull request by mc-cat-tty**
Reorganize code by splitting up each optimization into a separate function with a common behaviour:
 1. Check if the instruction is suitable for the optimisation
 2. Return immediately if not
 3. Continue if is suitable
 4. Return true if optimization has been applied
 5. Return false otherwise

### CODE REVIEW

**Comment by mc-cat-tty** [comment]
Refactor optAlgId by applying DRY programming principle

**Comment by mc-cat-tty** [comment]
Refactorized all opt passes with the following benefits:
 - increased readability
 - less code indentation by immediately exiting from the pass if the assumptions are not met
 - optMultiInstr generalized for the patterns that lead to nullification with adds and subs

**Comment by mc-cat-tty** [comment]
@ent0n29 @ch-fano aspetto la vostra revisione

**Comment by ent0n29** [comment]
@mc-cat-tty review done

**Comment by ent0n29** [comment]
now issue #5 is our priority

**Pull request merged**
